### PR TITLE
Fix MSD bug

### LINKED ISSUE #152: 02-multi_determinant not working
When trying to run the example in https://github.com/linusjoonho/ipie/tree/main/examples/02-multi_determinant I get back the following error message: 

> File "/ipie/estimators/local_energy_batch.py", line 101, in local_energy_batch
>     system, hamiltonian, walker_batch, trial
>   File "/ipie/estimators/local_energy_wicks.py", line 974, in local_energy_multi_det_trial_wicks_batch_opt
>     Lvo,
> ValueError: cannot assign slice from input of different size

The generation of the input file works, I see the error when trying to run AFQMC by calling 
> python /path/to/ipie/bin/ipie.py input.json > output.dat

### PR DESCRIPTION
**Pull request by fdmalone**
Fix bug in wicks code when nalpha != nbeta (also added unit test.)

Should fix #152

### CODE REVIEW

**Review by linusjoonho — COMMENTED** [review]
For closed shell, don't we gain by not storing alpha and beta intermediates separately?

**Comment by fdmalone** [comment]
This specialization isn't implemented. I think in the restricted MO basis we can probably also just build max(na,nb) intermediate and reuse?

**Comment by fdmalone** [comment]
Actually, do we ever need beta component of intermediates for PHMSD?

**Review by linusjoonho — APPROVED** [review]
LGTM

**Pull request merged**
